version: '3.8'
services:
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - '4445:4444'

  firefox:
    image: selenium/standalone-firefox:latest
    hostname: firfox
    privileged: true
    shm_size: 2g
    ports:
      - '4446:4444'